events { worker_connections 1024; }

http {
    upstream cluster_backends {
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://cluster_backends;
            # Añadimos la cabecera para ver qué contenedor responde
            add_header X-Backend-Server $upstream_addr;
        }
    }
}